# @package _global_
# DLC Large cluster configuration
# Paths
paths:
  root: /work/dlclarge2/ndirt-SegFM3D
  DATA_DIR: ${.root}/data
  RESULTS_DIR: ${.root}/ic_segmentation/results
  dataset: ${.DATA_DIR}/${dataset}
  dataset2d: ${.DATA_DIR}/${dataset}2d
  dataset2d_h5: ${.DATA_DIR}/${dataset}2d_h5
  #dataset2d_every_n_slice: ${.DATA_DIR}/${dataset}2d_every_n_slice
  dataset_stats: ${.DATA_DIR}/${dataset}/stats.pkl
  ckpts:
    save_dir: ${..RESULTS_DIR}/checkpoints
    medverse: ${..root}/checkpoints/Medverse.ckpt
    dino_vit: "facebook/dinov3-vitl16-pretrain-lvd1689m"
    dino_convnext: ${..root}/checkpoints/dinov3-convnext-large
    meddino_vit: ${..root}/checkpoints/med_dino_v3model.pth
    medsam2: null  # Set to local path or null to download from HuggingFace (wanglab/MedSAM2)
    patch_icl: ${..RESULTS_DIR}/checkpoints/best_model_28_01_26.pt
    # patch_icl_v2: ${..RESULTS_DIR}/checkpoints/scarlet-firefly-161/best_model.pt

# Cluster-specific training settings
train_batch_size: 48
val_batch_size: 48
training:
  num_workers: 18
