# @package _global_
# DLC Large cluster configuration
# Paths
paths:
  root: /work/dlclarge2/ndirt-SegFM3D
  DATA_DIR: ${.root}/data
  RESULTS_DIR: ${.root}/ic_segmentation/results
  totalseg: ${.DATA_DIR}/TotalSeg
  medsegbench: ${.DATA_DIR}/MedSegBench
  totalseg2d: ${.DATA_DIR}/TotalSeg2D
  totalseg_stats: ${.totalseg}/totalseg_stats.pkl
  ckpts:
    save_dir: ${..RESULTS_DIR}/checkpoints
    medverse: ${..root}/checkpoints/Medverse.ckpt
    dino_vit: "facebook/dinov3-vitl16-pretrain-lvd1689m"
    dino_convnext: ${..root}/checkpoints/dinov3-convnext-large
    meddino_vit: ${..root}/checkpoints/med_dino_v3model.pth
    medsam2: null  # Set to local path or null to download from HuggingFace (wanglab/MedSAM2)
    patch_icl: ${..RESULTS_DIR}/checkpoints/best_model_28_01_26.pt

# Cluster-specific training settings
train_batch_size: 32
val_batch_size: 32
training:
  num_workers: 16

logging:
  save_imgs_masks: false