# @package _global_
# NFS cluster configuration
# Paths
paths:
  root: /nfs/data/nii/data1/Analysis/camaret___in_context_segmentation/ANALYSIS_20251122
  DATA_DIR: ${.root}/data
  RESULTS_DIR: ${.root}/results
  medsegbench: ${.DATA_DIR}/medsegbench
  dataset: ${.DATA_DIR}/${dataset}
  dataset2d: ${.DATA_DIR}/${dataset}2d
  dataset2d_h5: ${.DATA_DIR}/${dataset}2d_h5
  dataset_stats: ${.DATA_DIR}/${dataset}/${dataset}_stats.pkl
  ckpts:
    save_dir: ${..RESULTS_DIR}/checkpoints
    medverse: /nfs/norasys/notebooks/camaret/repos/Medverse/Medverse.ckpt
    dino_vit: ${..root}/checkpoints/models--facebook--dinov3-vitl16-pretrain-lvd1689m/snapshots/ea8dc2863c51be0a264bab82070e3e8836b02d51
    dino_convnext: ${..root}/checkpoints/models--facebook--dinov3-convnext-large-pretrain-lvd1689m/snapshots/e959efa74c867491dcfe3ec3e4f97382e39025b3
    meddino_vit: ${..root}/checkpoints/med_dino_v3model.pth
    medsam2: null  # Set to local path or null to download from HuggingFace (wanglab/MedSAM2)
    patch_icl: ${..RESULTS_DIR}/checkpoints/best_model_28_01_26.pt
    patch_icl_v2: null #${..RESULTS_DIR}/checkpoints/peach-plasma-179/best_model.pt
# Cluster-specific training settings
train_batch_size: 200
val_batch_size: 200
training:
  num_workers: 16
